apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
#      volumes:
#        - name: redis-data-store
#          persistentVolumeClaim:
#            claimName: redis-pv-claim
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
#          volumeMounts:
#            - mountPath: "/data"
#              name: redis-data-store